### ISSUE TITLE
FetchAll >  where > ".deleted_at is null or .restored_at is not null" repeated many times in request

### ISSUE THREAD

**Issue by ariden** [lanetix/node-bookshelf-soft-delete#26]
Hello,

When we do a FetchAll on a table, 

if we see in BDD logs,
.deleted_at is null or .restored_at is not null 
is repeat many times in request, 

ex:

select "table1".\* from "table1" where ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) and ("table1"."deleted_at" is null or "table1"."restored_at" is not null) limit ?

**Comment by juliusza** [comment]
Thanks for the report. Will investigate.

**Comment by juliusza** [comment]
I'm not seeing this in tests:

```
  Model.fetchAll()
 sql: 'select "test".* from "test" where ("test"."deleted_at" is null or "test"."restored_at" is not null)'
```

you will have to provide more information about your settings.

**Comment by ariden** [comment]
In fact, I don't know if the problem came to our framework or softdelete or bookshelf. I will inspect.

We have many model. Each model has it  file where we do : 

module.exports = (bookshelf) => {
  // Add required plugins
  bookshelf.plugin(softDelete);
  // Model
  return (bookshelf.Model.extend(
    {
....
},
    {
      expose: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
      validation: {
...
}

Then, each model file including **bookshelf.plugin(softDelete); ** set a new :
> _and ("accounts"."deleted_at" is null or "accounts"."restored_at" is not null)_
in request.

Then, if i have 10 models files, i will have 10 '   _and ("accounts"."deleted_at" is null or "accounts"."restored_at" is not null) _  ' in my requests.

**Comment by ariden83** [comment]
Hello,

I do a fix. Could you give me rights to push a branch ? 
> pseudo : ariden or aparrochia

Thx.

**Comment by juliusza** [comment]
Hi, please create a pull request. Note that it has to come with tests if possible.

**Comment by ariden83** [comment]
Done

**Comment by fcarreiro** [comment]
@ariden Is this really a bug? I mean, what is happening is that you are calling `bookshelf.plugin` many times on the same bookshelf instance. I agree that maybe it is good to add a check to see if the plugin has already been added, but maybe you should consider having a file where you do something like:
```js
// file my-bookshelf.js
// [some knex stuff]
var bs = require('bookshelf')(knex);
var softDelete = require(...);
bookshelf.plugin(softDelete);

module.exports = bs;
```
then after that you can use
```
var mybs = require('./my-bookshelf');
```
and then simply pass that instance to your model files (removing the plugin call there).
