### ISSUE TITLE
Custom initialize function overwriting node-bookshelf-soft-delete's initialize function

### ISSUE THREAD

**Issue by BKStephens** [lanetix/node-bookshelf-soft-delete#28]
I have some code like:
```
var repository = require('./repo');

module.exports = repository.Model.extend({
  tableName: 'users',
  soft: true,

  initialize: function() {
    this.on('saving', this.validate);
  },

  validate: function() {
    ...
  }
});
```

After writing some tests, I discovered that destroy() was hard-deleting the records. After placing several console.log statements in node_modules/bookshelf-soft-delete/index.js, I discovered that the console.log in the initialize was not being hit.

I was eventually able to make soft-delete work with my custom initialize function with the following:
```
var repository = require('./repo');

module.exports = repository.Model.extend({
  tableName: 'users',

  initialize: function() {
    this.on('saving', this.validate);
    repository.Model.prototype.soft = true;
    repository.Model.prototype.initialize();
  },

  validate: function() {
    ...
  }
});
```

Does this seem like the best approach for using a custom initialize function with node-bookshelf-soft-delete? Would you accept a pull request to add some documentation about this to the README?

**Comment by juliusza** [comment]
I don't think it makes sense to modify Model prototype

```
repository.Model.prototype.soft = true;
```

all subsequent models will then inherit soft = true, will they not?

If you're willing to investigate this further, you might want to take a closer look at 
```
destroy: function (opts) {
```

looks like in your case this.softActivated should be false, but why?

**Comment by juliusza** [comment]
Looks like you're overriding plugin initialize function which applies setSoftDeleteOptions. What if you did something like this:

```
  initialize: function() {
    this.on('saving', this.validate);
    repository.Model.initialize();
  },
```

**Comment by juliusza** [comment]
Looks like you might be overriding plugins initialize function. What if you did something like this instead:

```
 initialize: function() {
    this.on('saving', this.validate);
    # This should set soft delete options on model
    repository.Model.initialize.apply(this, arguments);
  },
```

**Comment by BKStephens** [comment]
You are right, setting soft equal to true on the prototype could have side effects. I took your suggestion from your last comment and was able to get it to work like so:

```
var repository = require('./repo');

module.exports = repository.Model.extend({
  tableName: 'users',
  soft: true,

  initialize: function() {
    this.on('saving', this.validate);
    repository.Model.prototype.initialize.apply(this, arguments);
  },

  validate: function() {
    ...
  }
});
```

Thanks for the feedback! Would you like me to open a pull request to add some documentation about this to the README?

**Comment by juliusza** [comment]
Sure, let's document this.
