### ISSUE TITLE
We can't re-insert data (which has been deleted) if there is an unik column

### ISSUE THREAD

**Issue by ariden** [lanetix/node-bookshelf-soft-delete#29]
Hello,

We can't re-push datas in model if there is an (or many) **unik keys** on this model : 

ex: 
Model 'cars' (car_id, car_color, car_mark, car_number_plaque) > unik key ('car_number_plaque') 
data1 > '1b6079a7-7363-4de0-ad42-8af9d8c54e3d',  'green', 'citroen', '178ak83'
data2 > ...
data3 > ...

if we delete the data1 and create a new data with the same 'car_number_plaque' (unik key), 

we have a **conflict error**: 
{
  "code": "ConflictError",
  "message": "Key (car_number_plaque)=(178ak83) already exists."
}

Maybe, **node-bookshelf-soft-delete**, when we do an new **insert**, must have to verifiy if there is already an delete data, and reactive it rather than there is a **unik key*

**Comment by ariden** [comment]
I find a simple solution, it's to not include bookshelf.plugin(require('bookshelf-soft-delete')); in my problematic model :)

**Comment by juliusza** [comment]
You're not supposed to insert data with same ukey. Soft delete only marks row as deleted, that mean the ukey still exists.

**Comment by ariden** [comment]
You're not supposed to insert data with same ukey. > In BDD, you must could use unick key...

Another solution is to add a "**unick index key**" not including deleted_at field when it's not null.

Ex:  
CREATE UNIQUE INDEX uniq_email_unique ON accounts USING btree (email) WHERE deleted_at IS NULL
