### ISSUE TITLE
Transaction and options for `save` support

### ISSUE THREAD

**Issue by vellotis** [lanetix/node-bookshelf-soft-delete#32]
[index.js#L72](https://github.com/lanetix/node-bookshelf-soft-delete/blob/2e4a3788e5bf1051e707c267cf085f9489991cf7/index.js#L72) and [index.js#L91](https://github.com/lanetix/node-bookshelf-soft-delete/blob/2e4a3788e5bf1051e707c267cf085f9489991cf7/index.js#L91).

This plugin doesn't support transactions at the moment. But not only lack of transactions is the problem. As internally multiple different sequential events `destroying`, `updating`, `saving`, `updated`, `saved` and `destroyed` are being emitted while calling `destroy`. Only `destroyed` and `destroying` get options passed to.

I looked into the [`save`](https://github.com/tgriesser/bookshelf/blob/cecfa8e17a4a8d03c80ddc7834ef6157b372be89/src/model.js#L888) method. Following keys are referenced there
- options.method
- options.defaults
- options.patch - to only set deletd_at field
- options.require - to see if the update really was successful
- options.transacting - for transaction
- options.query (assignment)
- options.previousAttributes (assignment)

These options just have to be kept in mind. Seem to be pretti harmless to just:

``` js
/*72*/ return model.save(null, opts);

// and

/*91*/ return model.save(null, opts);
```

Best Regards. PR?

**Comment by Znarkus** [comment]
Added a PR for transaction support. #40

**Comment by juliusza** [comment]
Merged PR
