### ISSUE TITLE
Hard deleting row instead of soft delete

### ISSUE THREAD

**Issue by vaidehi-imedia** [lanetix/node-bookshelf-soft-delete#39]
Call plugin like this
bookshelf.plugin(require('bookshelf-soft-delete'))

Then in my model and i'm specifying my field like this:
bookself.Model.extend({
    soft: ['is_deleted']
});

This permanently deletes row from table instead of setting is_delete flag as true.
I'm using bookshelf 0.10.3 and bookshelf-paranoia 0.10.4 version.

Thanks in adavance

**Comment by juliusza** [comment]
On your bookshelf Model which you would like to mark for soft deletion:

soft: true

**Comment by vaidehi-imedia** [comment]
I tried with that also. But it's not working.

I've custom field called "is_deleted". So what configurations needs to be modified for the same?
